name: Rapha International Ministries / Mark White Ministries
favicon: null
layout_spectrum: 0.50812
typography_spectrum: 0.75361
title: 'Rapha International '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6d6d6d'
    - '#f2f2f2'
    - '#0731ff'
    - '#4f87fa'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
