name: 'Rapha International  '
favicon: null
layout_spectrum: 0.62004
typography_spectrum: 0.74278
title: 'Rapha International '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040309'
    - '#3a3f43'
    - '#c87549'
    - '#ddbe85'
    - '#1402b8'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
