name: Rapha International Ministries / Mark White Ministries
favicon: null
layout_spectrum: 0.25181
typography_spectrum: 0.75361
title: 'Rapha International '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#122021'
    - '#895d2e'
    - '#a3a1a2'
    - '#405b6e'
    - '#868080'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
