name: Rapha International Ministries / Mark White Ministries
favicon: null
layout_spectrum: 0.25181
typography_spectrum: 0.75361
title: 'Rapha International '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010e38'
    - '#fefef9'
    - '#3c406d'
    - '#6f839b'
    - '#a4dfe3'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
