name: Rapha International Ministries / Mark White Ministries
favicon: null
layout_spectrum: 0.25023
typography_spectrum: 0.82581
title: 'Rapha International '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16171c'
    - '#705e52'
    - '#c5b8a7'
    - '#ffffff'
    - '#ffd541'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
