name: Rapha International Ministries / Mark White Ministries
favicon: null
layout_spectrum: 0.13267
typography_spectrum: 0.75361
title: 'Rapha International '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040309'
    - '#3a3f43'
    - '#1600bb'
    - '#79705f'
    - '#ead18f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
