analytics: {}
color:
  brandColors:
    - '#000000'
    - '#6d6d6d'
    - '#f2f2f2'
    - '#0731ff'
    - '#4f87fa'
  brandStrength: 0.5
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.4375
cta: {}
layout_spectrum: 0.50812
name: Rapha International Ministries / Mark White Ministries
opengraph: {}
purpose: []
typography_spectrum: 0.75361
